# Generated by Django 6.0.6 on 2026-06-19 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_table'),
        ('dining_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dining_table.table'),
        ),
    ]
