# Generated by Django 6.0.6 on 2026-06-30 06:47

import authentication.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authentication.managers.CustomUserManager()),
            ],
        ),
    ]
