# Generated by Django 6.0.6 on 2026-06-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining_table', '0002_bill_public_id_table_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
