# Generated by Django 6.0.6 on 2026-06-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining_table', '0003_bill_deleted_at_table_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
