# Generated by Django 6.0.6 on 2026-06-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining_table', '0004_bill_is_deleted_table_is_deleted'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('table',), name='unique_active_bill_per_table'),
        ),
    ]
