# Generated by Django 6.0.6 on 2026-06-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category_public_id_item_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
