# Generated by Django 6.0.6 on 2026-06-19 05:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dining_table', '0001_initial'),
        ('menu', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])),
                ('instruction', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('O', 'Ordering'), ('W', 'Waiting'), ('D', 'Delivered')], default='O', max_length=1)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dining_table.bill')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='menu.item')),
            ],
        ),
    ]
