# Generated by Django 6.0.6 on 2026-06-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deleted_at',
        ),
    ]
